local Masque, MSQ_Version = LibStub("Masque", true)
local IconSize = 38

Masque:AddSkin("Unhalted", {
    API_VERSION = 110000,
    Backdrop = {
        Width = IconSize,
        Height = IconSize,
        Color = { 15 / 255, 15 / 255, 15 / 255, 1.0 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Backdrop.tga]],
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Icon = {
        Width = IconSize - 2,
        Height = IconSize - 2,
        Point = "CENTER",
        RelPoint = "CENTER",
        TexCoords =  {0.07, 0.93, 0.07, 0.93},
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Cooldown = {
        Width = IconSize - 2,
        Height = IconSize - 2,
        Color = { 0, 0, 0, 0.75 },
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Border = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 1.0 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Border.tga]],
        BlendMode = "BLEND",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Normal = {
        Width = IconSize,
        Height = IconSize,
        Color = { 0, 0, 0, 1.0 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Normal.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Checked = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 0.5 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Normal.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Highlight = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 0.25 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Pushed.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Pushed = {
        Width = IconSize,
        Height = IconSize,
        Color = { 0, 0, 0, 0.5 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Pushed.tga]],
        BlendMode = "BLEND",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    QuestBorder = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 0.8, 0, 1.0 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Quest_Border.tga]],
        Border = [[Interface\AddOns\Masque_Unhalted\Textures\Quest_Border.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    SearchOverlay = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 1 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Search_Overlay.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    NewItem = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 1 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\New_Item.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    SpellHighlight = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 0.5 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Highlight.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    SlotHighlight = {
        Width = IconSize,
        Height = IconSize,
        Color = { 1, 1, 1, 0.5 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Highlight.tga]],
        BlendMode = "ADD",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    ContextOverlay = {
        Width = IconSize,
        Height = IconSize,
        Color = { 0, 0, 0, 0.75 },
        Texture = [[Interface\AddOns\Masque_Unhalted\Textures\Pushed.tga]],
        BlendMode = "BLEND",
        Point = "CENTER",
        RelPoint = "CENTER",
        OffsetX = -0.1,
        OffsetY = 0.1,
    },
    Count = {
        Width = IconSize,
        Height = 12,
        JustifyH = "RIGHT",
        JustifyV = "BOTTOM",
        Point = "BOTTOMRIGHT",
        RelPoint = "BOTTOMRIGHT",
        OffsetX = -2,
        OffsetY = 4,
        DrawLayer = "OVERLAY",
    },
    HotKey = {
        Width = IconSize,
        Height = 12,
        JustifyH = "LEFT",
        JustifyV = "TOP",
        Point = "TOPLEFT",
        RelPoint = "TOPLEFT",
        OffsetX = 2,
        OffsetY = -2,
        DrawLayer = "OVERLAY",
    },
    Name = {
        Width = IconSize,
        Height = 12,
        JustifyH = "CENTER",
        JustifyV = "TOP",
        Point = "TOP",
        RelPoint = "TOP",
        OffsetX = 0,
        OffsetY = -2,
        DrawLayer = "OVERLAY",
    },

}, true)
